# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.9
install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/recipe_api/index.py"
  - export FLASK_DEBUG=1

script: sh bootstrap.sh && python -m unittest